package com.hrmsrevamp.constant;

/**
 * MessageEnum.
 */
public enum MessageEnum {
  USER_SIGNED_UP_SUCCESSFULLY,
  USER_SIGNED_IN_SUCCESSFULLY,
  USER_ALREADY_EXISTS,
  INVALID_EMAIL_OR_PASSWORD,
  DEVICE_ADDED_SUCCESSFULLY,
  USER_NOT_FOUND,
  INVALID_STATUS,
  USER_PROFILE_UPDATED,
  USER_FOUND,
  USER_DELETED,
  YOU_HAVE_ENTERED_AN_INVALID_EMAIL_ADDRESS,
  PASSWORD_RESET_SUCCESSFULLY,
  NEW_PASSWORD_CONFIRM_PASSWORD_MISMATCH,
  USER_DISABLED,
  INVALID_TOKEN,
  MOBILE_NUMBER_MUST_NOT_BE_NULL_OR_EMPTY,
  INVALID_MOBILE_NUMBER,
  INVALID_SIGN_IN_REQUEST,
  INVALID_CREDENTIAL,
  LOGGED_IN_USER_IS_INACTIVE,
  LOGGED_IN_USER_IS_INVALID,
  INVALID_REFRESH_TOKEN,
  NEW_DATA_STORED,
  UPDATED,
  NOT_FOUND,
  DATABASE_ERROR,
  APPRAISAL_CYCLE_LIST,
  DATA_RETRIEVED;
}
